### ISSUE TITLE
Studying

### ISSUE THREAD

**Issue by FelipeAugst** [ortizdavid/golang-fiber-webapp#1]

**Comment by ortizdavid** [comment]
There are more projects in this repository

**Comment by FelipeAugst** [comment]
Boa tarde,Ortiz! 
Me desculpe,ainda tenho dificuldades com Github e comentei sem querer. 
No mais muito obrigado mesmo! Eu tenho aprendido bastante sobre Go com este projeto.
Abraço!

**Comment by ortizdavid** [comment]
Boa noite, Felipe!

Sem problemas.
Ainda terá muito conteúdo.
Comecei a aprender Go recentemente. Mas decidi aprender com projectos.
Estudando a sintaxe não ajuda muito.
Vou partilhar sempre que poder

FelipeAugst ***@***.***> escreveu no dia quarta, 19/07/2023
à(s) 19:09:
